name: java-project
on:
  push: 
     branches: 
         - dev
jobs: 
 first: 
  runs-on: self-hosted
  steps: 
   - name: Git-checkout
     uses: actions/checkout@v4.1.7
   - name: Install java and maven packages
     run: | 
       sudo apt-get update -y
       sudo apt install default-jre -y
       cd /opt 
